apiVersion: v1
kind: Namespace
metadata:
  name: "postgres"
  labels:
    name: "postgres"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: postgres
spec:
  serviceName: "postgres-service"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          resources:
            limits:
              memory: "5Gi"
              cpu: "750m"
            requests:
              memory: "1Gi"
              cpu: "250m"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "123456"
            - name: POSTGRES_DB
              value: "book-swap"  # Название вашей базы данных
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: postgres-storage
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: "standard"  # Укажите ваш StorageClass, если требуется.
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
